// File: src/app/core/constants/api-endpoints.const.ts

export const API = {
  AUTH: {
    SEND_OTP:      '/auth/send-otp',
    VERIFY_OTP:    '/auth/verify-otp',
    REGISTER:      '/auth/register',
    REFRESH_TOKEN: '/auth/refresh-token',
    LOGOUT:        '/auth/logout',
  },
  SCRIPTS: {
    LIST:            '/scripts',
    DETAIL:          (id: string) => `/scripts/${id}`,
    VALIDATE:        '/scripts/validate',
    UPLOAD:          '/scripts/upload',
    STATUS:          '/scripts/status',
    VERSIONS:        (id: string) => `/scripts/${id}/versions`,
    SAMPLE_TEMPLATE: '/scripts/sample-template',
  },
  SESSIONS: {
    LIST:      '/sessions/history',
    CREATE:    '/sessions',
    VALIDATE:  (code: string) => `/sessions/validate/${code}`,
    JOIN:      '/sessions/join',
    LOBBY:     (id: string) => `/sessions/lobby/${id}`,
    READY:     '/sessions/ready',
    START:     (id: string) => `/sessions/${id}/start`,
    END:       (id: string) => `/sessions/${id}/end`,
    LEAVE:     (id: string) => `/sessions/${id}/leave`,
    COMPLETE:  (id: string) => `/sessions/${id}/complete`,
  },
  TURNS: {
    CURRENT:          (id: string) => `/turns/${id}/current`,
    SHIFT:            (id: string) => `/turns/${id}/shift`,
    VOICE_ANALYSIS:   (id: string) => `/turns/${id}/voice-analysis`,
    LISTENER_FEEDBACK:(id: string) => `/turns/${id}/listener-feedback`,
    RE_READ:          (id: string) => `/turns/${id}/re-read`,
  },
  MISTAKES: {
    LIST:             '/mistakes',
    SUMMARY:          '/mistakes/summary',
    GRAMMAR_PROGRESS: '/mistakes/grammar-progress',
  },
  REPRACTICE: {
    GENERATE:  '/repractice/generate',
    DETAIL:    (id: string) => `/repractice/${id}`,
    HISTORY:   '/repractice/history',
    ATTEMPT:   '/repractice/attempt',
    COMPLETE:  (id: string) => `/repractice/${id}/complete`,
  },
  USERS: {
    PROFILE:         '/users/profile',
    AVATAR:          '/users/profile/avatar',
    SESSION_DETAIL:  (id: string) => `/users/sessions/${id}/detail`,
    PROGRESS:        '/users/progress',
    STREAK:          '/users/streak',
    BADGES:          '/users/badges',
  },
  ADMIN: {
    DASHBOARD:       '/admin/dashboard',
    USERS:           '/admin/users',
    USER_DETAIL:     (id: string) => `/admin/users/${id}`,
    USER_STATUS:     '/admin/users/status',
    USER_NOTES:      '/admin/users/notes',
    USER_NOTES_LIST: (id: string) => `/admin/users/${id}/notes`,
    REPORTS:         '/admin/reports',
    USER_REPORT:     (id: string) => `/admin/reports/users/${id}`,
    EXPORT:          '/admin/reports/export',
  },
  DASHBOARD: '/dashboard',
};
